//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCSV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentCSV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPR-number.
        /// </summary>
        public static string CPRNr {
            get {
                return ResourceManager.GetString("CPRNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Direction.
        /// </summary>
        public static string EducationDirection {
            get {
                return ResourceManager.GetString("EducationDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction is not selected.
        /// </summary>
        public static string EducationDirectionIndexChecker {
            get {
                return ResourceManager.GetString("EducationDirectionIndexChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUX.
        /// </summary>
        public static string EUX {
            get {
                return ResourceManager.GetString("EUX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gf School.
        /// </summary>
        public static string GfSchool {
            get {
                return ResourceManager.GetString("GfSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GF School is not selected.
        /// </summary>
        public static string GfSchoolIndexChecker {
            get {
                return ResourceManager.GetString("GfSchoolIndexChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpr-number is Invalid.
        /// </summary>
        public static string InvalidCPRNr {
            get {
                return ResourceManager.GetString("InvalidCPRNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Invalid.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname is Invalid.
        /// </summary>
        public static string InvalidFirstname {
            get {
                return ResourceManager.GetString("InvalidFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname is Invalid.
        /// </summary>
        public static string InvalidLastname {
            get {
                return ResourceManager.GetString("InvalidLastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middlename is Invalid.
        /// </summary>
        public static string InvalidMiddlename {
            get {
                return ResourceManager.GetString("InvalidMiddlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber is Invalid.
        /// </summary>
        public static string InvalidPhonenumber {
            get {
                return ResourceManager.GetString("InvalidPhonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant contain ;.
        /// </summary>
        public static string InvalidSpecialInfo {
            get {
                return ResourceManager.GetString("InvalidSpecialInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you will save.
        /// </summary>
        public static string MessageBoxConfirm {
            get {
                return ResourceManager.GetString("MessageBoxConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Cancel.
        /// </summary>
        public static string MessageBoxConfirmCancel {
            get {
                return ResourceManager.GetString("MessageBoxConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Cancel.
        /// </summary>
        public static string MessageBoxConfirmCanceled {
            get {
                return ResourceManager.GetString("MessageBoxConfirmCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your info are new saved.
        /// </summary>
        public static string MessageBoxInfomationSavedString {
            get {
                return ResourceManager.GetString("MessageBoxInfomationSavedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access file, the file can already be open.
        /// </summary>
        public static string MessageBoxUnableToAccessFileError {
            get {
                return ResourceManager.GetString("MessageBoxUnableToAccessFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middlename.
        /// </summary>
        public static string Middlename {
            get {
                return ResourceManager.GetString("Middlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber.
        /// </summary>
        public static string Phonenumber {
            get {
                return ResourceManager.GetString("Phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpecialInfo.
        /// </summary>
        public static string SpecialInfo {
            get {
                return ResourceManager.GetString("SpecialInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanted Skp Location.
        /// </summary>
        public static string WantedSkpLocation {
            get {
                return ResourceManager.GetString("WantedSkpLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanted SKP Location is not selected.
        /// </summary>
        public static string WantedSkpLocationIndexChecker {
            get {
                return ResourceManager.GetString("WantedSkpLocationIndexChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
